DROP TABLE IF EXISTS`squad`;

CREATE TABLE `squad` (
	`id` BIGINT AUTO_INCREMENT,
	`first_name` VARCHAR(255) NOT NULL,
	`last_name` VARCHAR(255) NOT NULL,
	`position` VARCHAR(255) NOT NULL,
	`link` VARCHAR(255) NOT NULL,
	`age` INT NOT NULL,
	PRIMARY KEY(`id`)
);